
package com.qfedu.getCountryCityByIp;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>IP��ַ���� WEB ����</strong>�����й��͹�����֪��IP��ַ���ݣ���Ŀǰ��������IP��ַ���ݣ���¼�������ѳ���37���������ڲ��ϸ��º������У���IP��ַ�ڲ��ϱ仯����IP��ַ���ݲ�ѯ�����ο���</br>��IP��ַ����Web Services�벻Ҫ�����κ���ҵĿ�ģ�������Ҫ��<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">��ϵ����</a>����ӭ���������� QQ��8409035<br /><strong>ʹ�ñ�վ WEB ������ע�������ӱ�վ��http://www.webxml.com.cn/ ��л��ҵ�֧��</strong>��<br /><br />&nbsp;
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IpAddressSearchWebService", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "http://www.webxml.com.cn/WebServices/IpAddressSearchWebService.asmx?wsdl")
public class IpAddressSearchWebService
    extends Service
{

    private final static URL IPADDRESSSEARCHWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException IPADDRESSSEARCHWEBSERVICE_EXCEPTION;
    private final static QName IPADDRESSSEARCHWEBSERVICE_QNAME = new QName("http://WebXml.com.cn/", "IpAddressSearchWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.webxml.com.cn/WebServices/IpAddressSearchWebService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IPADDRESSSEARCHWEBSERVICE_WSDL_LOCATION = url;
        IPADDRESSSEARCHWEBSERVICE_EXCEPTION = e;
    }

    public IpAddressSearchWebService() {
        super(__getWsdlLocation(), IPADDRESSSEARCHWEBSERVICE_QNAME);
    }

    public IpAddressSearchWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IPADDRESSSEARCHWEBSERVICE_QNAME, features);
    }

    public IpAddressSearchWebService(URL wsdlLocation) {
        super(wsdlLocation, IPADDRESSSEARCHWEBSERVICE_QNAME);
    }

    public IpAddressSearchWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IPADDRESSSEARCHWEBSERVICE_QNAME, features);
    }

    public IpAddressSearchWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IpAddressSearchWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IpAddressSearchWebServiceSoap
     */
    @WebEndpoint(name = "IpAddressSearchWebServiceSoap")
    public IpAddressSearchWebServiceSoap getIpAddressSearchWebServiceSoap() {
        return super.getPort(new QName("http://WebXml.com.cn/", "IpAddressSearchWebServiceSoap"), IpAddressSearchWebServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IpAddressSearchWebServiceSoap
     */
    @WebEndpoint(name = "IpAddressSearchWebServiceSoap")
    public IpAddressSearchWebServiceSoap getIpAddressSearchWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "IpAddressSearchWebServiceSoap"), IpAddressSearchWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IPADDRESSSEARCHWEBSERVICE_EXCEPTION!= null) {
            throw IPADDRESSSEARCHWEBSERVICE_EXCEPTION;
        }
        return IPADDRESSSEARCHWEBSERVICE_WSDL_LOCATION;
    }

}
